name: hnh-matrix

volumes:
  ansible-colletions:

services:
  ansible:
    image: ghcr.io/hicknhack-software/ansible:noble-2.18.7
    volumes:
      - .:/etc/ansible/roles/hicknhack-software.matrix-synapse
      - ./tests/docker-sshkey:/root/.ssh/id_rsa
      - ansible-colletions:/root/.ansible/collections
    working_dir: /etc/ansible/roles/hicknhack-software.matrix-synapse
    command:
      - '/bin/bash'
      - '-c'
      - >-
        ansible-galaxy install -r tests/requirements.yml
        && ansible-playbook --inventory=tests/docker-inventory.ini tests/playbook.yml
    tty: true
    stdin_open: true
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=false
    links:
      - matrix_vm

  matrix_vm:
    image: ghcr.io/hicknhack-software/ansible-target:jammy
    privileged: true
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - ./tests/docker-sshkey.pub:/root/.ssh/authorized_keys
    ports:
      - 8008:8008
