---
  - include: setup_certificates.yml

  - name: Ensure Matrix Folders
    file:
      path: "{{ item }}"
      state: directory
      owner: "{{ matrix_synapse_user }}"
      group: "{{ matrix_synapse_user_group }}"
    with_items:
      - "{{ matrix_synapse_config_dir }}"
      - "{{ matrix_synapse_media_store_path }}"
      - "{{ matrix_synapse_uploads_path }}"

  - name: Configure Homeserver
    template:
      src: homeserver.yaml.j2
      dest: "{{ matrix_synapse_config }}"
      owner: "{{ matrix_synapse_user }}"
      group: "{{ matrix_synapse_user_group }}"
    notify: restart matrix-synapse

  - name: Additianal Homeserver Configuration
    template:
      src: "{{ item }}.j2"
      dest: "{{ matrix_synapse_config_dir }}/{{ item }}"
      owner: "{{ matrix_synapse_user }}"
      group: "{{ matrix_synapse_user_group }}"
    notify: restart matrix-synapse
    with_items:
      - server_name.yaml
      - report_stats.yaml
