---
  - include: setup_certificates.yml
  
  - name: Ensure Matrix Folders
    file:
      path: "{{ item }}"
      state: directory
      owner: "{{ matrix_synapse_user }}"
      group: "{{ matrix_synapse_user_group }}"
    with_items:
      - "{{ matrix_synapse_config_dir }}"
      - "{{ matrix_synapse_media_store_path }}"
      - "{{ matrix_synapse_uploads_path }}"
      
  - name: Configure Homeserver
    template:
      src: homeserver.yml.j2
      dest: "{{ matrix_synapse_config }}"
    notify: restart matrix-synapse