---
  - name: Configure database
    template:
      src: "database.yml.j2"
      dest: "{{ matrix_synapse_config_dir }}/database.yaml"
    notify: restart matrix-synapse

  - name: Configure enable_registration
    template:
      src: "enable_registration.yml.j2"
      dest: "{{ matrix_synapse_config_dir }}/enable_registration.yaml"
    notify: restart matrix-synapse

  - name: Configure registration_shared_secret
    template:
      src: "registration_shared_secret.yml.j2"
      dest: "{{ matrix_synapse_config_dir }}/registration_shared_secret.yaml"
    notify: restart matrix-synapse
    
  - name: Configure report_stats  
    template:
      src: report_stats.yml.j2
      dest: "{{ matrix_synapse_config_dir }}/report_stats.yaml"
    notify: restart matrix-synapse

  - name: Configure server_name
    template:
      src: server_name.yml.j2
      dest: "{{ matrix_synapse_config_dir }}/server_name.yaml"
    notify: restart matrix-synapse

  - inlcude: setup_certificates.yml