- name: Add Matrix repositories
  apt_repository:
    repo:  "deb https://packages.matrix.org/debian/ bionic main"
    state: present

- name: Add an apt signing key
  apt_key:
    url: https://packages.matrix.org/debian/matrix-org-archive-keyring.gpg
    #id: DE2DA058
    state: present

- name: Install prequisites
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential
    - python3-dev
    - libffi-dev
    - python3-pip
    - python3-setuptools
    - sqlite3
    - libssl-dev virtualenv
    - libjpeg-dev
    - libxslt1-dev

- include: apt_upgrade.yml

- name: Install matrix-synapse
  apt:
    name: matrix-synapse-py3
    state: present
  notify: restart matrix-synapse

- name: Set Synapse Cache Factor
  lineinfile:
    path: /etc/default/matrix-synapse
    regexp: SYNAPSE_CACHE_FACTOR
    state: present
    line: "SYNAPSE_CACHE_FACTOR={{ matrix_synapse_cache_factor }}"
  notify: restart matrix-synapse

- include: postgresql.yml

- include: configure.yml
