---
  - name: Add non-standard repositories
    apt_repository:
      repo: "{{ item }}"
      state: present
    with_items:
      - deb https://matrix.org/packages/debian/ xenial main
      - deb-src https://matrix.org/packages/debian/ xenial main

  - name: Add an apt signing key
    apt_key:
      url: https://matrix.org/packages/debian/matrix-org-archive-keyring.asc
      id: DE2DA058
      state: present

  - include: apt_upgrade.yml

  - name: Install matrix-synapse
    apt:
      name: matrix-synapse-py3
      state: present
    notify: restart matrix-synapse

  - name: Set Synapse Cache Factor
    lineinfile:
      path: /etc/default/matrix-synapse
      regexp: SYNAPSE_CACHE_FACTOR
      state: present
      line: "SYNAPSE_CACHE_FACTOR={{ matrix_synapse_cache_factor }}"
    notify: restart matrix-synapse

  - include: postgresql.yml

  - include: configure.yml
