---
- name: Install prequisites
  ansible.builtin.apt:
    state: present
    update_cache: true
    cache_valid_time: 86400
    name:
      - gpg
      - lsb-release
      - wget
      - apt-transport-https
      - python3-debian

- name: PostgreSql
  ansible.builtin.include_tasks: postgresql.yml

- name: Add Matrix repo
  ansible.builtin.deb822_repository:
    name: Matrix
    types: deb
    uris: ["https://packages.matrix.org/debian/"]
    suites: ["{{ ansible_distribution_release }}"]
    components: [main]
    architectures: [amd64]
    signed_by: "https://packages.matrix.org/debian/matrix-org-archive-keyring.gpg"
  register: repo_result

# note: apt_key is deprecated
# - name: Add an apt signing key
#   ansible.builtin.apt_key:
#     id: F473DD4473365DE1
#     url: https://packages.matrix.org/debian/matrix-org-archive-keyring.gpg
#     state: present

# - name: Add Matrix repositories
#   ansible.builtin.apt_repository:
#     repo: "deb https://packages.matrix.org/debian/ {{ ansible_distribution_release }} main"
#     state: present

- name: Install matrix-synapse
  ansible.builtin.apt:
    name: matrix-synapse-py3
    state: present
    update_cache: "{{ repo_result.changed | bool }}"
  notify: Restart matrix-synapse

- name: Configure
  ansible.builtin.include_tasks: configure.yml
