- name: Add an apt signing key
  apt_key:
    id: F473DD4473365DE1
    url: https://packages.matrix.org/debian/matrix-org-archive-keyring.gpg
    state: present

- name: Add Matrix repositories
  apt_repository:
    repo:  "deb https://packages.matrix.org/debian/ bionic main"
    state: present

- name: Install prequisites
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential
    - python3-dev
    - libffi-dev
    - python3-pip
    - python3-setuptools
    - sqlite3
    - libssl-dev
    - virtualenv
    - libjpeg-dev
    - libxslt1-dev
    - libicu-dev

- include: apt_upgrade.yml

- name: Install matrix-synapse
  apt:
    name: matrix-synapse-py3
    state: present
  notify: restart matrix-synapse

- include: postgresql.yml

- include: configure.yml
