---
  - name: Add non-standard repositories
    apt_repository:
      repo: "{{ item }}"
      state: present
    with_items:
      - deb http://ftp.debian.org/debian jessie-backports main
      - deb https://matrix.org/packages/debian/ jessie main
      - deb-src https://matrix.org/packages/debian/ jessie main

  - name: Add apt-key for jessie-backports and matrix
    apt_key:
      keyserver: pgpkeys.mit.edu
      id: "{{ item }}"
    with_items:
      - 8B48AD6246925553
      - 7638D0442B90D010
      - 47F0DF61

  # - name: Add an apt signing key
  #   apt_key:
  #     url: https://matrix.org/packages/debian/repo-key.asc
  #     keyserver: pool.sks-keyservers.net
  #     id: 47F0DF61 
  #     state: present
  
  - include: apt_upgrade.yml

  - name: Install requirements
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - apt-transport-https
      - lsof
      - curl
      - python
      - python-pip

  - name: Install requirements from jessie-backports
    apt:
      name: "{{ item }}"
      state: present
      default_release: jessie-backports
    with_items:
      - python-cffi
      - certbot

  - name: Install matrix-synapse
    apt:
      name: matrix-synapse
      state: present
    notify: restart matrix-synapse

  - name: Set Synapse Cache Factor
    lineinfile:
      path: /etc/default/matrix-synapse
      regexp: SYNAPSE_CACHE_FACTOR
      state: present
      line: "SYNAPSE_CACHE_FACTOR={{ matrix_synapse_cache_factor }}"
    notify: restart matrix-synapse

  - include: postgresql.yml
  
  - include: configure.yml

