---
  - name: Install Nginx
    apt:
      name: nginx
      state: present
  
  - name: Configure Nginx
    template:
      src: "nginx.conf.j2"
      dest: "/etc/nginx/sites-available/{{ matrix_synapse_domain }}"
    notify:
      - restart nginx
  
  - name: Clean sites-enabled/
    file:
      state: absent
      path: "/etc/nginx/sites-enabled/{{ item }}"
    with_items:
      - "{{ matrix_synapse_domain }}"
      - default
  
  - name: Link sites-available to sites-enabled
    file:
      src: "/etc/nginx/sites-available/{{ matrix_synapse_domain }}"
      dest: "/etc/nginx/sites-enabled/{{ matrix_synapse_domain }}"
      state: link
    notify: restart nginx
  
  #- import_tasks: certs.yml
