---
- name: Install PostgreSQL
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2

- name: Retrieve Postgresql Version
  shell: psql --version | grep -o -E "[0-9]{1,}\.[0-9]{1,}"
  register: psql_version_output

- name: Determine Postgresql Config Path
  set_fact:
    psql_config_path: "/etc/postgresql/{{ psql_version_output.stdout_lines[0] }}/main"

- name: Configure Host Based Access
  template:
    src: pg_hba.conf.j2
    dest: "{{ psql_config_path }}/pg_hba.conf"
    owner: "{{ matrix_synapse_psql_user }}"
    group: "{{ matrix_synapse_psql_group }}"
    mode: 0640
  notify: restart postgresql
  when: matrix_synapse_psql_trust_local_connections

- name: Create Database User Role
  postgresql_user:
    name: "{{ matrix_synapse_database_user }}"
    password: "{{ matrix_synapse_database_password }}"
  become: true
  become_user: "{{ matrix_synapse_psql_user }}"

- name: Create Database Tables
  postgresql_db:
    name: "{{ matrix_synapse_database_name }}"
    encoding: UTF-8
    lc_collate: C
    lc_ctype: C
    template: template0
    owner: "{{ matrix_synapse_database_user }}"
  become: true
  become_user: "{{ matrix_synapse_psql_user }}"

